### ISSUE TITLE
When I click on the buy now button I get a bug Error, the payment gets processed but the error dosen't show the orders page

### ISSUE THREAD

**Issue by cesareuseche** [CleverProgrammers/react-challenge-amazon-clone#16]
When I click on the buy now button the payment gets processed, but I get this error: **Unhandled Rejection (FirebaseError): Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in document users/62IdRaWYZNXkX4iZYDoXiRlBytf2/orders/pi_1I7crQIA89ysljXolGJcgaLK)**

Thank you in advance and it would mean the world to me if someone could help me.

}
  55 | }).then(({ paymentIntent }) => {
  56 |     //paymentIntent = payment confirmation
> 57 |     db
     | ^  58 |         .collection('users')
  59 |         .doc(user?.uid)
  60 |         .collection('orders'

**Comment by hahajska** [comment]
same problem, i copy&pasted everything from their github(not the links) and now it crashes :D

**Comment by hahajska** [comment]
please help

**Comment by hahajska** [comment]
@cesareuseche can you contact me on instagram? so we can maybe try to fix it? @tomas.s8

**Comment by ghilaslinz** [comment]
@cesareuseche   @TomasSchlogl  have you solved the problem, if yes how ?

**Comment by haroon437** [comment]
@cesareuseche @TomasSchlogl  @ghilaslinz same problem cp team please help us to solve this error  all of you agree

**Comment by haroon437** [comment]
Guys have you solved this error

**Comment by tej-1441** [comment]
Have anybody solve it
