### ISSUE TITLE
Stripe API error, Indian regulation law causing payment error

### ISSUE THREAD

**Issue by GourabSanyal** [CleverProgrammers/react-challenge-amazon-clone#28]
Developing an eCommerce with Stripe payment gateway, and facing this error every time.

As mentioned in here I have to provide the customer's` name`, `billing address`, `description`, and `shipping address`, otherwise, the payment will fail, it's a govt law regulated in India.

This is the error I am getting in Stripe API logs

`invalid_request_error - description
As per Indian regulations, export transactions require a description. More info here: https://stripe.com/docs/india-exports`

How do I fix this?

This is the `handleSubmit` which cause the data transfer to the backend:

`const handleSubmit = async (event) => {
            // do all the fancy stripe stuff...
            event.preventDefault();
            setProcessing(true);
    
            const payload = await stripe.confirmCardPayment(clientSecret, {
                payment_method: {
                    card: elements.getElement(CardElement),
                }
            }}            
            ).then(({ error, paymentIntent }) => {
                // paymentIntent = payment confirmation

                    db
                      .collection('users')
                      .doc(user?.uid)
                      .collection('orders')
                      .doc(paymentIntent.uid)
                      .set({
                          basket: basket,
                          amount: paymentIntent.amount,
                          created: paymentIntent.created,
    
                      })
        
                    setSucceeded(true);
                    setError(null)
                    setProcessing(false)
        
                    dispatch({
                        type: 'EMPTY_BASKET'
                    })
            
                    history.replace('/orders')
            },
            )
        
        }`

**Comment by GourabSanyal** [comment]
If you are getting the same error from India while using Stripe SDK, or from any other country which consists of certain government laws that won't let the API make the call to the backend, you can simply change the payment gateway to an online payment portal's SDK which is easier to set up.

In India it is Mobiquick, I will be researching more payment gateway-related stuff for this app. If you want to check the update you can go through my amazon-clone repo.

Cheers

**Comment by anirudh357** [comment]
Thanks bud for info
