### ISSUE TITLE
Firebase Error: Failed to compile: Module not found: Can't resolve 'firebase' in

### ISSUE THREAD

**Issue by druhotzt** [CleverProgrammers/react-challenge-amazon-clone#29]
Received the following error. Have been beating my head against a wall for about a week now. Not sure what I've done wrong. I've tried installing the tools, installing them globally, and installing them with administrator privileges. I started another project from scratch to see if I made any errors in what I was doing. I reinstalled my operating system to make sure that I hadn't screwed up my settings somehow. I even went to the written instructions and just copied and pasted into the file to make sure there weren't any spelling errors. For the life of me I can't figure out why I'm getting this error. Additionally, I'm not getting this error on my desktop computer, only on my laptop. When I open it with my desktop computer, everything compiles and works fine. Any help would be greatly appreciated.

Failed to compile.

./src/firebase.js
Module not found: Can't resolve 'firebase' in 'C:\Users\...\src'

```javascript
import firebase from "firebase";

const firebaseConfig = {

  apiKey: ****
  authDomain: ****
  projectId: ****
  storageBucket: ****
  messagingSenderId: ****
  appId: ****
  measurementId: ****
};

const firebaseApp = firebase.initializeApp(firebaseConfig);
const db = firebaseApp.firestore();
const auth = firebase.auth();

export { db, auth };
```

**Comment by druhotzt** [comment]
Figured it out finally!!!! for anyone else experiencing the same issue. firebase version 9 requires the following:

```javascript
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';
```

**Comment by anirudh357** [comment]
Thanks buddy
