### ISSUE TITLE
TypeError: firebaseApp.firestore is not a function

### ISSUE THREAD

**Issue by Amshitha-Nair** [CleverProgrammers/react-challenge-amazon-clone#31]
I am getting this error. Can u pls  help me and tell what to do to solve this issue ? I have also attached a pic.
This is the code -
import { initializeApp } from 'firebase/compat/app'
import firebase from 'firebase/compat/app';
import "firebase/firestore";
import '@firebase/auth';

const firebaseConfig = {
    apiKey: "......",
    authDomain: ".....",
    projectId: ".......",
    storageBucket: "......",
    messagingSenderId: ".......",
    appId: ".........."
  };

const firebaseApp = firebase.initializeApp(firebaseConfig);

const db = firebaseApp.firestore();
const auth = firebase.auth();

export { db, auth };

![error](https://user-images.githubusercontent.com/88432145/137530430-bf864a5c-fd67-4e2c-bef3-19ab75eccca1.PNG)

**Comment by beaulieuke** [comment]
This seems like a upgrade to v9 issue.

**Comment by siddharth1009maker** [comment]
@Amshitha-Nair  is the issue resolved ?
